### ISSUE TITLE
Adding Query Time Change % in results.csv

### ISSUE THREAD

**Issue by vviau** [cubewise-code/optimus-py#10]
Hi Marius,

In the optimus result csv file, there is a column RAM change % that is very handy to see the impact on the RAM:
![image](https://user-images.githubusercontent.com/25290041/94153974-fc122180-feaf-11ea-8277-a8c584968ea6.png)

It would be convenient to have a new column for the query time, like Query Time Change %.

If you have this column/calculation, for ticket #9 , you could check if RAM Change % < 0.01 and Query Time Change % < 0.01 then stop Optimus! 

Cheers,

Vincent

**Comment by MariusWirtz** [comment]
All % columns are removed. Only absolute values are left in the csv.
