### ISSUE TITLE
The iteration ID for each cube should restart from 1

### ISSUE THREAD

**Issue by vviau** [cubewise-code/optimus-py#11]
Hi Marius,

It's great that optimus supports multi cubes. I can see that for the first cube Employee Reporting, Optimus did 30 iterations (ID 1-> 29) but then for the next cube General Ledger did also 30 iterations (ID 30 -> 58).

![image](https://user-images.githubusercontent.com/25290041/94154804-d9ccd380-feb0-11ea-9876-17aa5b4d0fd1.png)

I think when doing iteration for a new cube the ID number should start back to 1, as you can see in the screenshot, it might be confusing as you would expect to find the first iteration as 1 in the chart for General Ledger but actually, it is 30.

If you have 5 or 10 cubes you want to optimize, the ID will quickly grow to 3 digits and it will be harder to read the chart.

Cheers,

Vincent

**Comment by MariusWirtz** [comment]
Thanks! This is addressed now
