### ISSUE TITLE
RuntimeError: Performance Monitor must be activated

### ISSUE THREAD

**Issue by vviau** [cubewise-code/optimus-py#15]
Hi Marius,

Currently if Performance monitor is not on, OptimusPy will try to get the RAM 4 times before generating the python error below:
```
Failed to retrieve RAM consumption. Waiting 15s before retry
Failed to retrieve RAM consumption. Waiting 15s before retry
Failed to retrieve RAM consumption. Waiting 15s before retry
Failed to retrieve RAM consumption. Waiting 15s before retry
Fatal error
Traceback (most recent call last):
  File "optimuspy.py", line 120, in main
    permutation_results += original_order.execute(reset_counter=True)
  File "C:\TM1py\optimus\executors.py", line 106, in execute
    return [self._evaluate_permutation(
  File "C:\TM1py\optimus\executors.py", line 69, in _evaluate_permutation
    ram_usage = self._retrieve_ram_usage()
  File "C:\TM1py\optimus\executors.py", line 92, in _retrieve_ram_usage
    raise RuntimeError("Performance Monitor must be activated")
RuntimeError: Performance Monitor must be activated
```
Screenshot below:
![image](https://user-images.githubusercontent.com/25290041/95747297-cf8d4080-0cca-11eb-99d5-1e309cb574f6.png)

Instead of waiting for 4*15sec and generating an error, it would be great if OptimusPy could check first if the parameter PerformanceMonitor = True:
![image](https://user-images.githubusercontent.com/25290041/95747524-30b51400-0ccb-11eb-9ec3-3957a17221c2.png)

If it is not True, OptimusPy should not even start and just ends with a message like. **OptimusPy requires PerformanceMonitor = True, please update the tm1s.cfg file before running OptimysPy again***

Cheers,

Vincent

**Comment by MariusWirtz** [comment]
We can't do that I'm afraid.

Some users may still use the Architect and turn on the PerformanceMonitor through right-click on the instance.
By waiting 15s we are essentially giving the user the opportunity to turn it on ad-hoc.

**Comment by rkvinoth** [comment]
Wait can be helpful, but we should reword the message thrown. Something like `Please check if Performance monitor is turned ON. Waiting 15s before retry` can be more straight-forward.

**Comment by MariusWirtz** [comment]
I just recently learned that the PerformanceMonitorOn field in the config is "in sync" with the PerformanceMonitor configuration in good old Architect.
I think Optimus can simply activate it in the beginning and turn it back to pre-state when done.
