### ISSUE TITLE
It would be nicer to have more logging.

### ISSUE THREAD

**Issue by rkvinoth** [cubewise-code/optimus-py#17]
For medium/ bigger size cubes, no logging is done between 
```
Starting analysis for cube '***'
Original dimension order for cube '***' is 
```
and
```
Completed analysis for cube '***'
Updated dimension order for cube '***' to [
```

Once they are hooked up for analysis it would be nicer to have logs written for every `update_storage_dimension_order` with the result.

**Comment by MariusWirtz** [comment]
Yeah, that's a fair point. I think we can add those log statements. I will add create a PR.

Thanks for bringing this up!
