### ISSUE TITLE
AttributeError: 'TM1Service' object has no attribute 'cells'

### ISSUE THREAD

**Issue by WHarper1** [cubewise-code/optimus-py#18]
Hello Marius,

I am currently trying to test optimus-py, however I get an error as soon as a cube is found that contains the view referenced in the command line call an error message occurs:

Skipping cube 'FCST Seasonality' since view 'z_Optimise' does not exist
Traceback (most recent call last):
  File "optimuspy.py", line 184, in <module>
    success = main(
  File "optimuspy.py", line 105, in main
    original_vmm, original_vmt = retrieve_vmm_vmt(tm1, cube_name)
  File "optimuspy.py", line 88, in retrieve_vmm_vmt
    return tm1.cells.execute_mdx_values(mdx)
AttributeError: 'TM1Service' object has no attribute 'cells'

**Comment by MariusWirtz** [comment]
Hi @WHarper1,

you need to upgrade TM1py to version 1.5. Just execute the statement below:
`pip install tm1py --upgrade`

**Comment by WHarper1** [comment]
Thanks Marius,
That sorted it.

**Comment by MariusWirtz** [comment]
Glad it works now. Please post it scatterplot here if you have any interesting findings!
