### ISSUE TITLE
optimus py unable to create csv

### ISSUE THREAD

**Issue by tomasfelcman** [cubewise-code/optimus-py#23]
Hi when running optimus.py (on macOS) I get following error for the first cube reordered:
_Traceback (most recent call last):
  File "optimuspy.py", line 183, in <module>
    success = main(
  File "optimuspy.py", line 150, in main
    optimus_result.to_csv(view_name, RESULT_CSV.format(cube_name, view_name, TIME_STAMP))
  File "/Users/tomasfelcman/Documents/Projects/TM1Py/optimus-py-master/results.py", line 91, in to_csv
    os.makedirs(os.path.dirname(file_name), exist_ok=True)
  File "/Applications/anaconda3/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)_

Is there any prerequisite or limitation of optimus.py to the OS? 
Thank you,
Tomas

**Comment by rkvinoth** [comment]
I believe the issue is here:
https://github.com/cubewise-code/optimus-py/blob/42feee336572199406f525687c539c52d3046122/optimuspy.py#L18

**Comment by tomasfelcman** [comment]
Hi Vinoth,
 you were right - the hard coded \\ works fow Windows only. I have created Pull request for the support of multiple OS by using Path().

Thank you,
Tomas

**Comment by MariusWirtz** [comment]
Solved with #25
