### ISSUE TITLE
Configparser error

### ISSUE THREAD

**Issue by wimgielis** [cubewise-code/optimus-py#26]
Hello Marius,

I am trying to run the tool on a model on my own laptop. However, the connection to TM1 cannot be establised. Would you happen to have an idea what it could be ? See the picture please (if that works). It's the one in Notepad++, the one in Notepad is the example file. Login in my TM1 model is also admin-apple
![configparser error](https://user-images.githubusercontent.com/17201709/99158217-c54ad180-26d0-11eb-86e6-3ebbd3c40a63.PNG)

**Comment by MariusWirtz** [comment]
Hi @wimgielis,

I think the script assumes that the `config.ini` is in the current directory.

Please try to navigate to the folder first and then execute it again.

**Comment by wimgielis** [comment]
Thanks, I got past that error. The script is running (for 2 cubes), I'll check back tomorrow morning ;-)

**Comment by wimgielis** [comment]
Still got an 'output': 
![image](https://user-images.githubusercontent.com/17201709/99158947-743edb80-26d8-11eb-8512-89f8ab2889a1.png)

**Comment by rkvinoth** [comment]
Turn on **performance monitor** from Architect or through **TM1 config** file.

**Comment by wimgielis** [comment]
Thanks, I indeed understood that the performance monitor had to be turned
on. Is is mentioned on the page at Github ? If not, it's probably best to
add it.

It's running now for 15 minutes, 1 cube has to be treated, 7 orderings have
been tested. I'm waiting for the results. 7 orderings did not yield a
better result than my manual (original) ordering. Keep you posted.

Also, I need to navigate to the folder of the ini configuration file first.
My cmd prompt opens from the C drive. I did a cd to the D drive, but it's
not accepted. Apparently we need to insert /d
cd /d "D:\Downloads\optimus-py-master"

Then the cd is accepted. I did not know that.

Best regards,

Wim


------

Best regards / Beste groeten,

Wim Gielis
MS Excel MVP 2011-2014
https://www.wimgielis.com <http://www.wimgielis.be>


Op zo 15 nov. 2020 om 06:35 schreef Vinoth Kumar Ravi <
notifications@github.com>:

**Comment by MariusWirtz** [comment]
We just added functionality to TM1py to turn on the performance monitor.
https://github.com/cubewise-code/tm1py/commit/03a7b9b25e5910466dca39c648c2365345a280ee

The idea is that Optimus would turn it on autonomously and turn it off after it's done.

Thanks for posting the directory issue. I will adjust the code so that no matter where Optimus is executed it searches the config.ini in the directory of the script.

**Comment by MariusWirtz** [comment]
It would be great if you could post the scatterplot here, once it's done. I'm curious about the results 🙂

**Comment by wimgielis** [comment]
Sure, give me a day or so. It's still running :-0


------

Best regards / Beste groeten,

Wim Gielis
MS Excel MVP 2011-2014
https://www.wimgielis.com <http://www.wimgielis.be>


Op zo 15 nov. 2020 om 14:57 schreef Marius Wirtz <notifications@github.com>:

**Comment by wimgielis** [comment]
It finished, successfully, thanks for that. A gain of 9 % in RAM and again 9% in query time, compared to a non-optimized version that originated from "experience". It's more of a "drill cube" containing also a line number dimension, to store individual financial "bookings" rather than monthly totals.

I have a Years dimension (2016 until 2022) in the Title section of the saved view. All these elements are in the subset/selection, but only 2020 shows. Does it matter for the calculations whether the dimension is in rows /columns / titles, and does it matter which element is selected in the titles / do we need to remove the other years ?

Results: a (long) account dimension goes from position 4 (out of 10) to the first position in the cube. That is rather against my common belief.

Maybe an option to build in: I am not going to change my Period dimension to the last but one position. Traditionally I have it right after the Year dimension. Would it be an idea to allow the user to fix certain orderings/configurations ? It would mean the script runs faster too. For instance, dimensions 1-2-3-4 cannot be changed, nor the measures dimension. All others can be pivoted.

![result](https://user-images.githubusercontent.com/17201709/99187109-ee14aa80-2754-11eb-8ec8-4fb72a48147d.png)

**Comment by wimgielis** [comment]
![image](https://user-images.githubusercontent.com/17201709/99187273-f3262980-2755-11eb-8882-919b6ea830af.png)

**Comment by wimgielis** [comment]
The csv file format is not so ideal, I would say. We need to do a "Text to columns" if the field separator is different.
The numbers cannot be interpreted with a different decimal separator.
Is there an option to output as an Excel file instead ?

**Comment by wimgielis** [comment]
The "issue" can be closed

**Comment by MariusWirtz** [comment]
Thanks for sharing the results @wimgielis. Very interesting!
I will close this issue and open dedicated new ones for the topics that you brought up.

For the performance, only the element that is actually selected in the titles matters.
I know for sure that it makes a big difference if a dimension is in the rows/columns vs. the titles.
I am not sure if there is a difference in query speed when it comes to rows vs. columns.

>Results: a (long) account dimension goes from position 4 (out of 10) to the first position in the cube. That is rather against my common belief.

Is it perhaps because in your view you had a leaf element from the account dimension selected in the titles?

> Would it be an idea to allow the user to fix certain orderings/configurations ?

Yeah, we should allow the users to fixate certain positions. I like that idea. I will open a separate issue for it.

> Is there an option to output as an Excel file instead?

Not yet :)
