### ISSUE TITLE
Leave certain positions untouched

### ISSUE THREAD

**Issue by MariusWirtz** [cubewise-code/optimus-py#27]
There should be way to configure Optimus to leave certain positions in a dimension order of a cube untouched. E.g. dimension 1 must always be time.

**Comment by ivankulman** [comment]
@MariusWirtz I am working on this right now for one of our own projects and planning to raise a pull request once this is developed and tested.

I have a question on the input parameter and reordering logic.


1. Move/keep the "excluded" dimension to the Display Order Position - this is the current behaviour as the ordering always starts with the display order.
2. Keep the "excluded" dimension to the current Storage order - this is what I would understand is correct.
3. Provide a map of dimensions to optimus py: {"dim1":1, "dim2":2} etc so there is no ambiguity.
4. Something else.

**Comment by ivankulman** [comment]
I've currently developed the 2nd option, providing a list of comma split dimensions using -d (for dimensions) parameter. probably not the best letter for it 😄 will try to get a pull request this week if that's an acceptable approach.

**Comment by MariusWirtz** [comment]
I think the 2nd option sounds reasonable! So does `-d`

Feel free to open the PR
