### ISSUE TITLE
strange optimal order results

### ISSUE THREAD

**Issue by tomasfelcman** [cubewise-code/optimus-py#31]
Hi,
 I have done some testing of the optimus py and there have been strange results for on of the cubes:

ID,Mode,Is Best,Mean Query Time,RAM,Dimension1,Dimension2,Dimension3,Dimension4
--
1,Original Order,False,0.09010518,4195328,MetrikaPL,Perioda,Verze,Rok
2,Iterations,False,0.08690834,4195328,Verze,Perioda,Rok,MetrikaPL
3,Iterations,False,0.08564043,4195328,MetrikaPL,Verze,Rok,Perioda
4,Iterations,True,0.08697665,2098688,MetrikaPL,Perioda,Verze,Rok
5,Iterations,False,0.08890033,4195328,MetrikaPL,Perioda,Rok,Verze
6,Iterations,False,0.08666933,2098688,MetrikaPL,Perioda,Verze,Rok
7,Iterations,False,0.08690453,2098688,Perioda,MetrikaPL,Verze,Rok
8,Iterations,False,0.15419602,2098688,Verze,Perioda,MetrikaPL,Rok

It looks like the optimal order is the original order - which should be correct as I run optimus againts the same view for multiple times. But the weird thing is the measures between the lines 1 and 4 differ highly in RAM.
It that because of the low overall RAM (2 MB - I have changed the scale in code)?

Thank you for any ideas...
T.

**Comment by MariusWirtz** [comment]
Hi @tomasfelcman,

I can imagine two reasons why the same order shows two different RAM values.

1. Your version of TM1 is old and there were issues in the API, that were perhaps addressed in later versions.
Which version are you using?

2. As you said, the overall memory with 2MB is so small, that the additional 2MB could simply be some kind of one-off effect that normally would go unnoticed.
If you add more data to the cube (> 100MB), can you reproduce the behavior

**Comment by tomasfelcman** [comment]
Hi @MariusWirtz,
1. I am using TM1 version 11.6.00001.1
2. I have done testing on other model and the results show that the exact optimal order changes depending on the number of optimalizations applied - below there are 2 consecutive runs of the optimus (with executions = 100) on the same cube. What I get from it is that the  deviation in time of approx 0.2s is too high. Or is there any other reasonable explanation why the query time should differ when testing the order vs when the order is original?
1st run:
ID,Mode,Is Best,Mean Query Time,RAM,Dimension1,Dimension2,Dimension3,Dimension4,Dimension5,Dimension6
--
**1,Original Order,False,0.22805786,33551360,MetrikaSkutecnost,Produkt,Rok,Verze,Perioda,ObchodniLinie**
2,Iterations,False,0.24817157,58716416,ObchodniLinie,Perioda,Rok,Verze,Produkt,MetrikaSkutecnost
3,Iterations,False,0.21970034,33551360,MetrikaSkutecnost,ObchodniLinie,Rok,Verze,Produkt,Perioda
4,Iterations,False,0.21576059,50328064,MetrikaSkutecnost,Perioda,ObchodniLinie,Verze,Produkt,Rok
5,Iterations,False,0.21968853,50328064,MetrikaSkutecnost,Perioda,Rok,ObchodniLinie,Produkt,Verze
6,Iterations,False,0.20742643,41939712,MetrikaSkutecnost,Perioda,Rok,Verze,ObchodniLinie,Produkt
7,Iterations,False,0.20023453,33551360,MetrikaSkutecnost,Perioda,Rok,Verze,Produkt,ObchodniLinie
**8,Iterations,True,0.19970298,33551360,MetrikaSkutecnost,Perioda,Rok,Verze,Produkt,ObchodniLinie**
9,Iterations,False,0.20335364,33551360,Perioda,MetrikaSkutecnost,Rok,Verze,Produkt,ObchodniLinie
10,Iterations,False,0.20059443,33551360,Rok,Perioda,MetrikaSkutecnost,Verze,Produkt,ObchodniLinie
11,Iterations,False,0.20047033,33551360,Verze,Perioda,Rok,MetrikaSkutecnost,Produkt,ObchodniLinie
12,Iterations,False,0.22881889,33551360,Produkt,Perioda,Rok,Verze,MetrikaSkutecnost,ObchodniLinie
13,Iterations,False,0.22807837,33551360,MetrikaSkutecnost,Produkt,Rok,Verze,Perioda,ObchodniLinie
14,Iterations,False,0.22126651,33551360,MetrikaSkutecnost,Perioda,Produkt,Verze,Rok,ObchodniLinie
15,Iterations,False,0.22868764,33551360,MetrikaSkutecnost,Perioda,Rok,Produkt,Verze,ObchodniLinie
16,Iterations,False,0.22525859,33551360,MetrikaSkutecnost,Perioda,Rok,Verze,Produkt,ObchodniLinie
17,Iterations,False,0.24491036,33551360,MetrikaSkutecnost,Rok,Produkt,Verze,Perioda,ObchodniLinie
18,Iterations,False,0.23021317,33551360,MetrikaSkutecnost,Verze,Rok,Produkt,Perioda,ObchodniLinie
19,Iterations,False,0.24348354,33551360,MetrikaSkutecnost,Produkt,Rok,Verze,Perioda,ObchodniLinie

2nd run
ID,Mode,Is Best,Mean Query Time,RAM,Dimension1,Dimension2,Dimension3,Dimension4,Dimension5,Dimension6
--
**1,Original Order,False,0.22390771,33551360,MetrikaSkutecnost,Perioda,Rok,Verze,Produkt,ObchodniLinie**
2,Iterations,False,0.23050857,58716416,ObchodniLinie,Perioda,Rok,Verze,Produkt,MetrikaSkutecnost
3,Iterations,False,0.25624442,33551360,MetrikaSkutecnost,ObchodniLinie,Rok,Verze,Produkt,Perioda
4,Iterations,False,0.23232508,50328064,MetrikaSkutecnost,Perioda,ObchodniLinie,Verze,Produkt,Rok
5,Iterations,False,0.23044181,50328064,MetrikaSkutecnost,Perioda,Rok,ObchodniLinie,Produkt,Verze
6,Iterations,False,0.20704448,41939712,MetrikaSkutecnost,Perioda,Rok,Verze,ObchodniLinie,Produkt
**7,Iterations,True,0.19519186,33551360,MetrikaSkutecnost,Perioda,Rok,Verze,Produkt,ObchodniLinie**
8,Iterations,False,0.20607400,33551360,MetrikaSkutecnost,Perioda,Rok,Verze,Produkt,ObchodniLinie
9,Iterations,False,0.21736300,33551360,Perioda,MetrikaSkutecnost,Rok,Verze,Produkt,ObchodniLinie
10,Iterations,False,0.23007751,33551360,Rok,Perioda,MetrikaSkutecnost,Verze,Produkt,ObchodniLinie
11,Iterations,False,0.22727907,33551360,Verze,Perioda,Rok,MetrikaSkutecnost,Produkt,ObchodniLinie
12,Iterations,False,0.23911035,33551360,Produkt,Perioda,Rok,Verze,MetrikaSkutecnost,ObchodniLinie
13,Iterations,False,0.22741055,33551360,MetrikaSkutecnost,Produkt,Rok,Verze,Perioda,ObchodniLinie
14,Iterations,False,0.23776639,33551360,MetrikaSkutecnost,Perioda,Produkt,Verze,Rok,ObchodniLinie
15,Iterations,False,0.22818959,33551360,MetrikaSkutecnost,Perioda,Rok,Produkt,Verze,ObchodniLinie
16,Iterations,False,0.22294044,33551360,MetrikaSkutecnost,Perioda,Rok,Verze,Produkt,ObchodniLinie
17,Iterations,False,0.21731436,33551360,MetrikaSkutecnost,Rok,Produkt,Verze,Perioda,ObchodniLinie
18,Iterations,False,0.22327495,33551360,MetrikaSkutecnost,Verze,Rok,Produkt,Perioda,ObchodniLinie
19,Iterations,False,0.22803450,33551360,MetrikaSkutecnost,Produkt,Rok,Verze,Perioda,ObchodniLinie

**Comment by MariusWirtz** [comment]
Hi @tomasfelcman,

Thanks for the feedback.
I understand that the RAM values are now deterministic. I'm glad that part works.
For the query speed, I assume this is just "noise".  0.2 sec is probably too quick considering that the request and response also have to go through the network. 
If you used a larger cube view, I think we will see more speaking values.
