### ISSUE TITLE
Number of Interation

### ISSUE THREAD

**Issue by ZzRotivZz** [cubewise-code/optimus-py#34]
I'm using the optimus-py in my system, and I have a cube with 6 dimension, when I use the optimus-py it tests 19 interations, but with 6 dimension we have a possible number of 6 factorial (720) interations, So Why it only tests 19, and how we know that the best is one of this 19 and not one of the other 701 the we do not have tested.

**Comment by rkvinoth** [comment]
You gotta read [this ](https://code.cubewise.com/optimuspy)

**Comment by ZzRotivZz** [comment]
Thanks
