### ISSUE TITLE
Avoiding password in config.ini

### ISSUE THREAD

**Issue by tomasfelcman** [cubewise-code/optimus-py#36]
Hi,
 Would it be possible to enable password saving to the config.ini file? It is purely for safety reasons.
e.g. Add parameter to prompt for password...?
Thank you

**Comment by MariusWirtz** [comment]
Hi @tomasfelcman,

is it OK for you if we introduce a new optional argument: `-p` / `--password`, that can be used to pass the password instead of registering it in the config.ini?

**Comment by tomasfelcman** [comment]
Perfect!
