### ISSUE TITLE
Do not skip cubes with dims with string elements

### ISSUE THREAD

**Issue by tomasfelcman** [cubewise-code/optimus-py#37]
Hi,
 Would it be possible not to skip cubes that have a dims with string elements? The expected behaviour is:
If the dim with strings is not the latest -> no string value is stored and thus any permutation can be run.
If the dim with strings is the latest, keep it latest (possible related ER) and run permutations of all the other dims.
Thank you

**Comment by MariusWirtz** [comment]
Hi @tomasfelcman,

thanks for the feedback.

Regarding point1, are you saying that you have a scenario where dimensions 2 or 3 in a cube of 5 dimensions contain string elements? 
This setup should best be avoided. I believe it's a good practice to have a dedicated measure dimension in each cube and have string elements **only** in the measure dimension.

Regarding point2, if the last dimension of a cube contains string elements, the last position is fixated. However, for all other positions Optimus attempts to find the most suitable dimension.
Is this not how Optimus behaves in your setup?

**Comment by tomasfelcman** [comment]
ad1) Unfortunately there are some situations where we have Cube(Version, Period, CostCenter,MeasureXYZ, Measure ABC). Another use case is having special Period element dedicated for comments on the lines (no matter how "bad" is sounds/looks/behaves). (you can replace bad with your favorite hate word).

ad2) My apologies, it seems this falls into Ad1) when I retested it with different model. 

Thank you

**Comment by MariusWirtz** [comment]
We haven't actually tested this case. I will do more testing for scenario 1 and see if we can provide a quick fix.
