### ISSUE TITLE
I get the TypeError 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by il66ezov** [cubewise-code/optimus-py#41]
After a few "Evaluated order" messages, the script aborts with the following error message:

Fatal error
Traceback (most recent call last):
  File "C:/Users/qlikadm/IdeaProjects/optimus-py/optimus-py-master/optimuspy.py", line 167, in main
    optimus_result = OptimusResult(cube_name, permutation_results)
  File "C:\Users\qlikadm\IdeaProjects\optimus-py\optimus-py-master\results.py", line 127, in __init__
    self.best_result = self.determine_best_result()
  File "C:\Users\qlikadm\IdeaProjects\optimus-py\optimus-py-master\results.py", line 227, in determine_best_result
    process_speed_range = [result.median_process_time(result.process_name) for result in self.permutation_results]
  File "C:\Users\qlikadm\IdeaProjects\optimus-py\optimus-py-master\results.py", line 227, in <listcomp>
    process_speed_range = [result.median_process_time(result.process_name) for result in self.permutation_results]
  File "C:\Users\qlikadm\IdeaProjects\optimus-py\optimus-py-master\results.py", line 73, in median_process_time
    median = statistics.median(self.process_times_by_process[process_name])
TypeError: 'NoneType' object is not subscriptable

**Comment by MariusWirtz** [comment]
Hi @il66ezov,

sorry for the late reply.

Can you please provide the command to execute the script with all parameters?
This will help me to replicate the error

**Comment by AlexanderDvoynev** [comment]
Hi,

I have the same error. The command is:
`python optimuspy.py -i="Serv1" -v="Optimus" -e="10" -f="True"`

I've tried to add  `print (process_name)` to median_process_time: it returns None

What is the meaning of --process parameter in optimuspy.py? Should it be left blank?

**Comment by MariusWirtz** [comment]
Hi, 

we recently added a new feature to OptimusPy. Now the process runtime is also considered. In the resulting plot the size of the points in the scatterplot represents the runtime of the process.

If the process runtime is not relevant for you, you can provide a dummy process without code in it.

**Comment by MariusWirtz** [comment]
Hi @AlexanderDvoynev,

if fixed the issue that occurs when no process_name is provided and I updated the readme. 
Thanks for re-reporting the issue. I appreciate it!

Please re-open if the issue persists after upgrading to the latest master branch.
