### ISSUE TITLE
Making Optimys Faster!

### ISSUE THREAD

**Issue by vviau** [cubewise-code/optimus-py#9]
Hi Marius,

Great work on Optimus, I just tried it and it is working well.

I just tried it on a small cube and it took 5 min to run, I could see that after the 10th iteration, the Query time and Ram haven't changed much but Optimus still did 30 more iterations. It would be handy sometimes if you are short in time to have a parameter to enable a "fast" mode.

Something like python optimuspy.py -i=tm1srv01 -v=Optimus -e=15 **-fast=true**

If fast = true then Optimus will stop if the RAM Change < 1% and Query Time Change < 1% (or 5%)

Cheers,

Vincent

**Comment by MariusWirtz** [comment]
The latest master branch has `fast` mode (-f/--fast). It only determines the first and last positions. That saves a lot of time.
